### PR TITLE
infrastructure/update-github-templates

### PR DESCRIPTION
**Pull request by hawkticehurst**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [x] Provide context of changes.

As part of a change across all of CDP's main repositories, I'm updating all of the GitHub issues and PR templates to improve readability and clarity of guidance.

- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Review by JacksonMaxfield — APPROVED** [review]

**Comment by JacksonMaxfield** [comment]
@hawkticehurst did you want these to be the same as the other repos new templates? They currently are different from the others. These still have the 5 checkboxes.

**Comment by hawkticehurst** [comment]
Oh.. huh. On my end it looks like I had deleted the checkboxes from the PR template?

**Comment by hawkticehurst** [comment]
Screen Shot 2021-08-11 at 4 46 44 PM

**Comment by JacksonMaxfield** [comment]
Oh yea. weird GitHub shows it now.

**Comment by JacksonMaxfield** [comment]
:shrug: :shrug: who knows. Or maybe I was just looking at it incorrectly.

**Pull request merged**
